spring:
  application:
    name: demo

  mail:
    host: smtp.gmail.com
    port: 587
    username: clnvrd@gmail.com
    password: nezt mgcz jeoy ovze
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

auth:
  code-expiration-millis: 1800000